name: Zip Release

on:
  push:
    tags: "v*"

jobs:
   upload_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
   
    - name: Create ZIP
      run: |
        mkdir -p io_ebmf_export
        7z a -mx9 io_ebmf_export.zip io_ebmf_export
   
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: io_ebmf_export.zip
